#%RAML 1.0 Trait
queryParameters:
    title:
      type: string
      required: false
    description:
      type: string
      required: false    
    provider:
      type: string
      required: false    
    type:
      type: string
      required: false    
    SKU:
      type: string
      required: false    
