#%RAML 1.0 NamedExample
values: 
  title: XBox One 
  description: Console
  type: Game
  provider: 507f1f77bcf86cd799439011
  price: 25.00
  cost: 25.00
  SKU: "01120000"
  barCode: 978-1-4028-9462-6
  weight: 2kg
  rateCodeSH: 3917.40.90
  characteristics:
    -
      type: color
      value: black
  
  
  
