#%RAML 1.0 NamedExample
values: 
  products:
    - #product 1
        id: 1
        title: XBox One 
        description: Console
        type: Game
        provider: 507f1f77bcf86cd799439011
        price: 25.00
        cost: 25.00
        SKU: "01120000"
        barCode: 978-1-4028-9462-6
        weight: 2kg
        rateCodeSH: 3917.40.90
        characteristics:
          - #characteristic 1
            type: color
            value: black
    - #product 2
        id: 2
        title: XBox One 
        description: Console
        type: Game
        provider: 507f1f77bcf86cd799439011
        price: 25.00
        cost: 25.00
        SKU: "01120000"
        barCode: 978-1-4028-9462-6
        weight: 2kg
        rateCodeSH: 3917.40.90
        characteristics:
          - #characteristic 2
            type: color
            value: black